//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.LineaCompras = new HashSet<LineaCompra>();
        }
    
        public int idCompra { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaCompra> LineaCompras { get; set; }
    }
}
